package com.example.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Entity
@Data
public class ProductEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private double price;

    public ProductEntity() {
    }

    public ProductEntity(String name, double price) {
        this.name = name;
        this.price = price;
    }

    public String getIdDocument() {
        return id.toString();
    }
    // Getters and Setters if needed (could be auto-generated by Lombok)
}
